//API Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "id": 3312101073,
    "name": "apotekerq",
    "email": "apotekerq@gmail.com",
    "password": "apotekerq",
    "confPassword": "apotekerq",
    "role": "apoteker"
}


###
//API Get all users
GET http://localhost:5000/users


###
//API Get single Data users ambil uuid
GET http://localhost:5000/users/6c4d0262-97ec-4dcc-b175-b92b638c381b


//upadate user
###
PATCH  http://localhost:5000/users/50e8493e-2b1e-4aca-8d1a-3b8ee9acf4a8
Content-Type: application/json

{
    "id": 6289519113444,
    "name": "apotek",
    "email": "apotek143@gmail.com",
    "password": "apotek143",
    "confPassword": "apotek143",
    "role": "apoteker"
}


###
//deleted user
DELETE http://localhost:5000/users/359105d5-7aa0-4d7b-8e84-afa22aae01cf


###
//LOGIN USER (sebagai admin)
// kalau login sebagai admin kita dapat crud data suer
// karena yang diperbolehkan untuk crud hanya admin yang di atur pada middelware
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin"
}

###
//LOGIN USER (sebagai apoteker)
// kalau login sebagai apoteker kita tidak dapat mengakses data user
// dikarenakan data user hanya dapat diakses pada admin yang di atur pada middelware
POST http://localhost:5000/login
Content-Type: application/json

# {
#     "email": "apotek143@gmail.com",
#     "password": "apotek143"
# }

 {
    "email": "apoteker@gmail.com",
     "password": "apoteker"
 }


###
//session login
GET http://localhost:5000/me


###
//logout
DELETE http://localhost:5000/logout


###
//get data obat all
GET http://localhost:5000/obat


###
//get data berdasarkan uuid
GET http://localhost:5000/obat/e528852f-be49-4918-a7ec-6cb8a65b5466


###
//menghapus data obat
DELETE http://localhost:5000/obat/4bea3853-5ed1-47e7-9d45-5a8a027b8a7a


###
//get berita all
GET http://localhost:5000/berita


###
//get berita byid
GET http://localhost:5000/berita/7d59e76e-107d-4272-89ba-fe7e2d5744d8


###
//menghapus data berita
DELETE http://localhost:5000/berita/7d59e76e-107d-4272-89ba-fe7e2d5744d8



###
//get data obat all tanpa loginn
GET http://localhost:5000/obats


###
//get data obat all tanpa login ngambil berdasarkan id
GET http://localhost:5000/obats/90475914-2b18-4049-b159-f9d685977e41



###
//get data obat all tanpa loginn
GET http://localhost:5000/beritas


###
//get data obat all tanpa login ngambil berdasarkan id
GET http://localhost:5000/beritas/c2b007a5-bc22-4a9f-8af5-d967ee2cb989
